jaffle_shop:
  target: dev
  outputs:
    dev:
      type: redshift
      host: default.935206693453.us-east-1.redshift-serverless.amazonaws.com
      user: admin
      password: 1234=Qwer19q3
      port: 5439
      dbname: dev
      schema: public
      threads: 1
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 10 # default 10 seconds
      ra3_node: true # enables cross-database sources